
services:
  web:
    build: .
    container_name: odoo17
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./odoo-addons:/mnt/extra-addons
      - ./odoo-backups:/odoo-backups
      - ./odoo-base:/usr/lib/python3/dist-packages/odoo/addons
      - ./odoo-data:/var/lib/odoo
      - ./odoo-etc:/etc/odoo
      - ./odoo-log:/var/log/odoo

  db:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
