
services:
  web:
    build: .
    container_name: odoo17
    depends_on:
      - db
    ports:
      - "80:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./odoo-addons:/mnt/extra-addons
      - ./odoo-data:/var/lib/odoo
      - ./etc:/etc/odoo
      - ./odoo-backups:/odoo-backups

  db:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

# volumes:
#   doo-addons:
#   odoo-data:
#   postgres-data:
